### ISSUE TITLE
تدوین فاز چهارم -  سی شارپ

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#18]
فاز چهارم با محوریت آشنایی با سی شارپ تدوین شود

موارد پیشنهادی برای فاز چهارم:

- [x] آشنایی با سینتکس مقدماتی سی شارپ
- [x] آشنایی با یونیت تست در سی شارپ
- [x] آشنایی با Linq

<p dir='rtl'>
پیشنهاد می کنم در این فاز هم کماکان وارد بحث  TDD نشیم
</p>

**Comment by mhaghighat20** [comment]
<p dir='rtl'>
مهدی اصرار داشت برنامه کارآموزی کاملا بر مبنای dotnet core پیش بره و نیازی به نصب و راه اندازی Visual Studio نداشته باشه
با این موضوع موافق هستین؟
</p>
@ahmadsalimi @mostmand @mahdimalverdi

**Comment by mhaghighat20** [comment]
موارد پیشنهادی برای فاز چهارم:

- [ ] آشنایی با سینتکس مقدماتی سی شارپ
- [ ] آشنایی با یونیت تست در سی شارپ
- [ ] آشنایی با Linq

**Comment by mhaghighat20** [comment]
<p dir='rtl'>
بچه ها مطمئن هستین همه چیز بر مبنای dotnet core به خوبی پیش میره؟ مثلا بجه هایی که لینوکس دارن آیا می تونن در فاز های بعدی 
MS SQL Server رو نصب کنن یا مثلا بحث Entity Framework اوکی هست؟

مشکلات عجیب و غریب یه وقت پیش نیاد وسط کار؟ @mahdimalverdi 
</p>

**Comment by mahdimalverdi** [comment]
مگه نیازی هست SqlServer نصب کنن؟
خودمون نصب می کنیم یه جا در اختیارشون میزاریم
البته اگه بخوان روی لینوکس هم میشه نصب بشه
فقط می مونه SSMS که اونو ایده ای ندارم
اما EfCore حتی با Sqlite هم جوابه!

**Comment by mostmand** [comment]
به نظرم اگه قراره چنین اتفاقی بیفته یکیمون بره تمام چیزای لازم روی لینوکس رو نصب کنه که اگه کسی از بچه‌ها به مشکل خورد بتونه مشکلش رو حل کنه

**Comment by mostmand** [comment]
اگه قراره در آینده واسه dotnet framework توسعه داده باشه از همین اول بگیم ویژوال استودیو نصب کنن

**Comment by mhaghighat20** [comment]
<p dir='rtl'>
من فکر می کنم ویژوال استادیو بالاخره یه جایی لازم میشه و با vscode به تنهایی نمیشه جلو رفت اما مهدی میگه دیباگ vscode چیزی از ویژوال استادیو کم نداره و کل برنامه کارآموزی رو بدون ویژوال استادیو باشیم، واقعا نمی دونم با این شرایط چه باید کرد!
</p>

**Comment by mahdimalverdi** [comment]
آره مطمئنم
من یه دور تست کردم اگه می خواین شما هم یه دور تست کنید
من لینک ها رو می دم یکی دیگه چک کنه ببینه می تونه باهاش کار کنه یا نه

**Comment by mahdimalverdi** [comment]
علی الخصوص یکی از بچه ها که کمتر با دات نت کور کمتر آشنایی داشته باشه بهتره

**Comment by mostmand** [comment]
بچه‌ها 
Jetbrains Rider
هم هست که خیلی عالیه

**Comment by mahdimalverdi** [comment]
حقیقتش هدفم ازش اینه که بچه ها روی یه محیط هم جاوا بزنن هم سی شارپ هم تایپ اسکریپت
الان با محمدحسین قیصریه صحبت کردم قرار شد تو لینوکس تست کنه کل کار رو

**Comment by mhaghighat20** [comment]
باشه پس بعد از جواب محمد حسین قیصریه تدوین رو شروع کن مهدی
@mahdimalverdi

**Comment by mhgheisarieh** [comment]
فردا سعی میکنم کلا رو لینوکس ماجرا رو بالا بیارم و تست کنم ببینم چه طور میشه!
