### ISSUE TITLE
تدوین فاز پنجم - TDD

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#19]
<div dir="rtl">

موارد پیشنهادی فاز:
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ آشنایی با TDD
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ آشنایی عمیق تر از فاز سوم با اصول SOLID
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ نحوهٔ ساخت پروژه class library و xunit
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ بازنویسی پروژه سرچ با زبان سی شارپ و با رویکرد TDD

قبل از تدوین فاز موارد فاز سوم رو مرور کنین

</div>

**Comment by mahdimalverdi** [comment]
بهتر نیس اول TDDبا جاوا به بچه ها یاد داده بشه؟

**Comment by mhaghighat20** [comment]
نه موافق نیستم چون برنامه فشرده هست و سینتکس جاوا و سی شارپ خیلی نزدیکه

راستی احتمالا محسن اینو انجام میده

**Comment by mahdimalverdi** [comment]
خب اگه محسن انجام می ده بهتر نیس جاوا باشه؟

**Comment by mhaghighat20** [comment]
<div dir='rtl'>
بچه ها توی فاز سوم با یونیت تست توی جاوا آشنا شدن، اگه بعد از یادگرفتن سی شارپ صرفا بخوان یونیت تست بنویسن خیلی کار خسته کننده ای هست و بهتره در کنار یونیت تست سی شارپ 
TDD
هم یادبگیرن
</div>

**Comment by mhaghighat20** [comment]
متاسفانه بخاطر حجم زیاد کار های جدیدی که برای محسن پیش اومده گفت نمی تونم اینو تدوین کنم

**Comment by mahdimalverdi** [comment]
این فاز باید برای هفته اول آماده شده باشه!

**Comment by ahmadsalimi** [comment]
تغییرات لازم در این فاز اعمال شد
@mhaghighat20

**Comment by mhaghighat20** [comment]
<p dir='rtl'>
با توجه به وضعیتی که سر git به وجود اومد و این که تصور من از سطح بچه ها یکم بالاتر از واقعیت بود به نظرم این فاز هم احتمالا نیاز به کارگاه داره، مخصوصا در مورد نحوه انجام TDD، ران کردن تست ها و کار کردن با پروژه های Class Library.
</p>

**Comment by mhaghighat20** [comment]
<p dir='rtl'>
فعلا لیبل Workshop needed میزنم اگه نظر دیگه ای داشتین بگین
</p>

**Comment by ahmadsalimi** [comment]
<div dir="rtl">
در مورد نحوه انجام TDD
چون من خودم خیلی تجربه ندارم بنظرم یکی که تجربه بیشتری داره کارگاه رو بذاره. ولی تست و class lib
و ایناش رو اوکی ام من
</div>

**Comment by mhaghighat20** [comment]
<p dir='rtl'>
باشه پس یه کارگاه برای آموزش همه زیرساخت های لازم مثل xUnit و class lib و ... بذار، برای TDD هم از ویدیو یوتیوب استفاده می کنیم

</p>

**Comment by ahmadsalimi** [comment]
البته مهدی تو کارگاه دیروز اشاره کرد و پروژه classlib و xuint ساخت و unit test هم نوشت باهاش. فک می‌کنین باز هم نیاز به کارگاه داریم؟
