### ISSUE TITLE
اضافه شدن لینک یک ویدیوی خوب برای Inverted Index

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#2]
<div dir="rtl">

به نظرم نیازه برای مفهوم Inverted Index یک ویدیوی خوب اضافه کنیم می تونیم هم خودمون کارگاه بذاریم و توضیح بدیم اما با توجه به این که خیلی مقدماتی هست و ویدیو های قوی توی اینترنت هست پیشنهاد می کنم صرفا از ویدیوی آماده استفاده کنیم.

</div>

**Comment by mhaghighat20** [comment]
هم لینک یوتیوب و هم لینک دیدئو بذاریم که بچه ها راحت باشن

**Comment by mahdimalverdi** [comment]
میشه هم یه کانال زد تو آپارات و کل فیلم ها رو اونجا آپلود کرد بعدش به منبعش هم رفرنس داد اینجوری هم قشنگ یه دسته میشه هم حقوق کپی رایت رو رعایت کردیم هم بچه ها نیاز به فیلترشکن و اینجور مسائل ندارن
