### ISSUE TITLE
تدوین فاز ششم - CI

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#21]
<p dir='rtl'>
آشنایی با CI و راه اندازی pipeline
</p>

- [x] آشنایی با مفهوم CI
- [x] درک نیاز به CI
- [x] ساخت و راه اندازی پایپلاین روی ریپازیتوری سی شارپ شامل:
  - [x] بیلد
  - [x] اجرای تست‌ها
  - [x] محاسبه کاوریج
- [x] پابلیش کد Class Library
  - [x] آشنایی با پکیج و پروژه های Class Library
  - [x] درک مزایای پکیج نسبت به کد های کنسول و ...
  - [x] ساخت پکیج نوگت با استفاده از پایپلاین و پابلیش آن

**Comment by mahdimalverdi** [comment]
داکر هم داخلش گفته بشه لطفا به درد بچه ها می خوره و به نظرم مناسب اینجاس

**Comment by ahmadsalimi** [comment]
> 
> 
> داکر هم داخلش گفته بشه لطفا به درد بچه ها می خوره و به نظرم مناسب اینجاس

خب در این صورت تسک رو از من بگیرید. من خودم مایلم یاد بگیرم داکر رو :)))))))

**Comment by mahdimalverdi** [comment]
خب بقیه رو برو داکر هم کمکت می کنیم

**Comment by mhaghighat20** [comment]
> داکر هم داخلش گفته بشه لطفا به درد بچه ها می خوره و به نظرم مناسب اینجاس

من موافق نیستم کلا از اسکوپ این فاز خارجه و واقعا در حد ران کردن پایپلاین ساده نیازی به یادگیری مفاهیم داکر نیست

**Comment by mhaghighat20** [comment]
<p dir='rtl'>
احمد جان به نظرت آیا این فاز نیاز به کارگاه داره؟ اگه داره لیبل Workshop needed بزن
</p>

**Comment by ahmadsalimi** [comment]
نمی‌دونم. بنظرم شفاف گفتم مراحلی که باید طی کنن رو، باز اگر نیازی هست بنظرتون بذاریم. کلا برعکس طراحیش که خیلی وقت گرفت، انجام دادنش وقت گیر نیست خیلی.
یعنی کارگاه هم اگر بذاریم نیم ساعته جمع میشه.
