### ISSUE TITLE
تدوین فاز هفتم - الاستیک سرچ

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#24]
<div dir='rtl'>
بعد از این که در فاز اول بچه‌ها با مفهوم
Inverted Index
آشنا شدن و اونو پیاده سازی کردن میخواهیم در این فاز آن ها را با 
elasticsearch
آشنا کنیم.
</div>

اهداف فاز آشنایی با این موارد هست:

- [x] درک اهمیت و دلایل محبوبیت موتور های جستجویی شبیه الاستیک در سال‌هال اخیر
- [x] مقدمه‌ی غیر فنی بر الاستیک سرچ و ماهیت آن
- [x] مثال هایی از تاثیر الاستیک سرچ در حوزه‌های مختلف
  - [x] جستجوی داخلی سایت‌ها و نرم افزار های مختلف
  - [x] جمع آوری و تحلیل لاگ‌ها در تیم‌های DevOps
  - [x] سایر حوزه‌ها به دلخواه طراح فاز
- [x] راه اندازی الاستیک سرچ
- [x] راه اندازی کیبانا
- [x] آشنایی با کانسپت‌های اصلی الاستیک سرچ ترجیحا به صورت Practical
  - [x] مفاهیم اولیه مثل داکیومنت و شارد و ایندکس و کلاستر و ریپلیکا و ...
  - [x] مفاهیم مربوط به پردازش متن مثل آنالایزر و استاپ ورد و ...
  - [x] انواع کوئری‌ها
    - [x] جستجوی ساده
    - [x] جستجوی فازی
    - [x] جستجوی روی سایر دیتاتایپ‌ها
    - [x] کوئری‌های بازه
    - [x] کوئری‌های اگریگیشن
- [x] سایر موارد به تشخیص طراح فاز

پیشنهاد می‌شود در این فاز اصلا به اتصال با الاستیک از طریق سی شارپ وارد نشویم

**Comment by mahdimalverdi** [comment]
یه پیشنهاد دارم نمی دونم چقدر خامه اما تجربه این چند روزی بوده که درگیر پروژه دانشگاهم
به نظرم برای هر تیم 4 تا سرور کوچیک بگیریم و به هر تیم بدیم
بعد بچه ها سعی کنن این ها رو باهم کلاستر کنن و دیتا روش بریزن و تفاوت ها رو مشاهده کنند و بفهمن اصلا فرق لوسین با الستیک چیه

**Comment by mhaghighat20** [comment]
بهش فکر می کنیم اما دقت کن توی این فاز اصلا حجم داده سنگین نیست و همه چیز می تونه روی الاستیک لوکال اتفاق بیفته
