### ISSUE TITLE
تدوین فاز نهم - برنامه‌نویسی وب

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#26]
<div dir='rtl'>
پیشنهاد می‌شود این فاز حول آشنایی با 
asp.net core
و 
angular
باشد
</div>

چک لیست اهداف این فاز:
- [x] آشنایی با aspnet core
- [x] آشنایی با انگولار

پیشنهاد می‌شود خروجی این فاز تبدیل برنامه کنسولی که در فاز هشتم به الاستیک سرچ متصل شده است  به یک وبسایت با یک صفحه ی ساده ی جستجو (مثل صفحه ساده گوگل) باشد

پیاده سازی آتوکامپلیت کوئری جستجو ی کاربر (مثل گوگل) می‌تواند یک آیتم امتیازی در پایان این فاز باشد

**Comment by mahdimalverdi** [comment]
این فاز باید به دو یا سه فاز بشکنه و قابل جمع شدن دریک فاز نیس
بچه ها تا میان مفهوم رست رو بفهمن یک یا دو فاز طول کشیده
حالا بعدش بگیریم انگولار رو بخوایم بگیم و تبدیل جیسون و ....

**Comment by mhaghighat20** [comment]
<div dir='rtl>
راستش من فکر میکنم خیلی از بچه هایی که توی کارآموزی قبول شدن از قبل با مفهوم 
REST
و حتی بالا آوردن یک وبسایت ساده آشنا هستن، اگه فکر می کنی حجم فاز زیاده می‌تونی بخش بندی اش کنی اما با توجه به این که کل فاز یک مفهوم برنامه‌نویسی وب داره به نظرم به دو یا چند فاز مختلف شکسته نشه
</div>

**Comment by mahdimalverdi** [comment]
با این بخش از صحبت که آشنایی دارن مخلافم چون حتی یکی از عزیزان نیس آشنایی نداشته باشه ما موظف هستیم این مفهوم رو براش جا بندازیم

**Comment by mahdimalverdi** [comment]
حداقل دو فاز بشه
یکی اینکه رست و Asp core آموزش داده بشه
یکی اینکه انگولار آموزش داده بشه

**Comment by rsangin** [comment]
به نظر منم جدا بشه. بچه هایی که پارسال هم اومده بودن خیلی با مفاهیم رست و سریالیزیشن آشنا نبودن.

**Comment by mahdimalverdi** [comment]
دقیقا! 
البته می تونیم مدت زمان این فاز رو گسترش بدیم!
رضا جان میشه زحمت بکشی یه داک براش آماده کنی چیزایی که نیازه و پول ریکوئست بزی؟

**Comment by rsangin** [comment]
کلا دارم بررسی میکنم که هم چی بگیم بهشون و هم پروژه هایی که تعریف میکنیم به چه شکلی باشه. سعی میکنم تا آخر هفته یه داک آماده کنم

**Comment by mahdimalverdi** [comment]
خیلی ممنون لطف می کنی
