### ISSUE TITLE
برنامه ریزی Onboarding

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#27]
<div dir='rtl'>
با توجه به اهمیت بسیار زیاد
Onboarding
در کارآموزی مخصوصا برای دانشجویان عزیزی که این کارآموزی اولین مواجهه اون‌ها با صنعت هست نیاز مبرمی به تدوین این برنامه داریم.

تدوین این برنامه بسیار چالشی خواهد بود و نیاز به مطالعه قبلی داره چون تمام اتفاقات در فضای ریموت و مجازی میفته، پیشنهاد می‌کنم قبل از شروع حتما برنامه آنبوردینگ ریموت شرکت گیتلب رو مطالعه کنین

https://about.gitlab.com/handbook/people-group/general-onboarding/onboarding-buddies/
https://gitlab.com/gitlab-com/people-group/employment-templates/-/blob/master/.gitlab/issue_templates/onboarding.md

پیشنهاد می‌کنم <strong>خروجی این قسمت تمپلیت ایشوی Onboarding </strong>کداستار باشه به این صورت که هر کارآموز اون رو کپی می‌کنه و در گیتهاب یک ایشو با همون محتوا درست می‌کنه و مراحل رو جلو میبره برای آشنایی با تدوین برنامه به صورت ایشو تمپلیت می‌تونین فاز دوم پروژه رو ببینین که یک فایل شرح پروژه داره و یک فایل ایشو تمپلیت:

https://github.com/Star-Academy/codestar-internship/blob/master/Projects/Search-Phase2.md
https://github.com/Star-Academy/codestar-internship/blob/master/Projects/issue-template-Search-Phase2.md

</div>

مواردی که پیشنهاد می‌کنم در تدوین این برنامه در نظر گرفته شود:
- [ ] کاهش استرس و سردرگمی کارآموز در ابتدای کار
- [ ] آشنا شدن اون‌ها با کارآموزان و سایر اعضای ستاره
- [ ] آشنایی کارآموز با نقش و مسئولیت‌های خود
- [ ] در نظر گرفتن راهی برای پیگیری مشکلات کارآموزان به ویژه در روز‌های اول مثل gitlab onboarding buddy

**Comment by mahdimalverdi** [comment]
باید در این جلسه منتورها و راهبرها به طور کامل معرفی راه دسترسی بهشون ساعات دسترسی بهشون و هم گروهی هاشون به طور کامل اعلام بشه
باید بچه ها در جلسه با منتورها و راهبر ها صمیمی بشن تا بتونیم قدم اول قوی ای برداریم

**Comment by mhaghighat20** [comment]
<div dir='rtl'>
اصل کار تدوین تمپلیت ایشوی Onboarding هست
</div>
