### ISSUE TITLE
تدوین فاز دهم - Transaction Visualizer

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#28]
<div dir='rtl'>
پیشنهاد می‌کنم در این فاز مباحث مرتبط با ویژوالایز گراف در وب رو مطرح کنیم. از نظر فنی فکر می‌کنم مناسب باشه یک وبسایت 
aspnet
 تعدادی تراکنش رو داشته باشه و به صورت گرافی که راس های اون حساب های بانکی و یال های اون تراکنش‌های مرتبط با اون حساب هاست رو در بر بگیره
</div>

اهداف این فاز آشنایی با موارد زیر هست:
- [x] آشنایی با اهمیت ویژوالایز کردن در تحلیل داده
- [x] آشنایی با لایبرری‌های ویژوالایز گراف
- [x] استفاده از یکی از لایببری‌ها و نمایش گراف روی صفحه

**Comment by mahdimalverdi** [comment]
قبلش نیازه که انگولار یاد گرفته باشن وگرنه خیلی اذیت میشن

**Comment by mahdimalverdi** [comment]
و فقط مختص به یه فاز نمیشه

**Comment by mhaghighat20** [comment]
فاز ۹ رو ببین #26

**Comment by mhaghighat20** [comment]
یه سوال آیا میشه قسما انگولار گراف ویژوالایز رو در
Github pages
دیپلوی کرد؟ که قابل نمایش روی اینترنت به همه باشه و نیاز به کلون کد و بیلد اون نباشه؟

**Comment by rsangin** [comment]
تراکنش ها قراره تو الستیک ریخته بشه؟ برای این قسمت نیاز به داک و یا کارگاه ندارید؟
