### ISSUE TITLE
تدوین فاز یازدهم - Node Expand

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#29]
<div dir='rtl'>
این فاز مناسب یک تیم چهار نفره هست که زیرساخت‌های لازم مرتبط با الاستیک و ویژوالایزر رو در فاز های قبلی توسعه داده باشن

در این فاز چند صد حساب بانکی و چند هزار تراکنش بانکی بین اون حساب‌ها رو در الاستیک وارد می‌کنیم، سپس با وارد کردن شماره حساب، کاربر می‌تونه حساب‌های مربوط رو به صورت راس گراف روی صفحه بندازه

همچنین کاربر می‌تونه یک راس گراف (که معادل یک حساب بانکی هست) رو اکسپند کنه و تمام حساب‌های دیگه که باهاش تراکنش داشتن رو توی محیط گراف ببینه

</div>

چک لیست فاز:
- [x] ایمپورت تراکنش ها در الاستیک
- [x] اکسپند نود گراف

**Comment by asalehi99** [comment]
ایمپورت یک دیتاست ساده به فاز ده منتقل،
بچه‌ها در فاز یازده دیتاست اصلی را منتقل می‌کنند
