### ISSUE TITLE
مشکل چک باکس ها در مارک داون فارسی

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#3]
من موارد فاز اول پروژه رو به صورت چک لیست اضافه کردم، تیم های کارآموزی اونو کپی می کنن هر کدوم یک ایشو باز می کنن و توی ایشوی خودشون این رو پیست می کنن و روی چک لیست جلو میرن اما به نظر میاد چک لیست با فارسی مشکل داره

کسی ایده ای داره چطوری این مشکلو حل کنیم؟

**Comment by mhaghighat20** [comment]
احمد من الآن فهمیدم یه مشکل جدید داریم، این فیچر به درد بخور رو با استفاده از اموجی  از دست میدیم:
https://docs.github.com/en/github/managing-your-work-on-github/about-task-lists

![image](https://user-images.githubusercontent.com/13956923/87866657-a98d2400-c999-11ea-95db-449d6e44b1a2.png)

**Comment by mhaghighat20** [comment]
من چند تا حالت رو میذارم اینجا تست کنیم:

- [x] تسک تست یک
- [ ] تسک تست دو

<div dir="rtl">

- [x] تسک تست یک
- [ ] تسک تست دو

</div>


<p dir="rtl">

- [x] تسک تست یک
- [ ] تسک تست دو

</p>

**Comment by ahmadsalimi** [comment]
خب این نشون دادن Progress فک کنم برای issue ها هست فقط. برای یه فایل ماکدان معمولی نمی‌دونم باشه یا نه. ولی اگر برای تسک ها اینجوری issue باز کنیم، اشکالی نداره که اون رو از حالت آخر استفاده کنیم.

**Comment by mhaghighat20** [comment]
اساسی موضوع رو حل کردم:
https://github.com/Star-Academy/codestar-internship/pull/14/files
