### ISSUE TITLE
برگزاری بازی کاهوت

### ISSUE THREAD

**Issue by mahdimalverdi** [Star-Academy/codestar-internship#35]
نیاز است در میان افتتاحیه یک بازی صورت بگیرد لطفا ایده های خود را در این مورد در این ایشو بیان کنید

**Comment by mhaghighat20** [comment]
جوان ترین و پیر ترین فرد ستاره با گزینه های جذاب

یکی دو تا سوال در مورد آمار مثلا تعداد امیرکبیری های کارآموز

**Comment by mhaghighat20** [comment]
یکی دو تا سوال توی این فاز:
کدوم یک از موارد زیر رو در کارآموزی تجربه نمی کنین:

کار تیمی جدی
یادگیری الاستیک سرچ
رقابت در میزان دویدن
یادگیری فریمورک ری اکت

**Comment by mhaghighat20** [comment]
یک ایده دیگه مثلا اون عکسی که از مجموعه مصاحبه ها درست کردم رو بذاریم بگیم  در شکل زیر چند نفر می بینید
