### ISSUE TITLE
فرشید نوشی

### ISSUE THREAD

**Issue by mostmand** [Star-Academy/codestar-internship#36]
<div dir="rtl" align='right'>

  
# فرآیند خوش‌آمدگویی

#### ورودت رو به فرآیند خوش‌آمدگویی کارآموزی مجازی کداستار تبریک می‌گیم!

ما خیلی خوشحالیم که در دوره‌ی ما حضور داری!
در این دوره از ابزار Github برای مدیریت و اشتراک گذاری تسک‌هایت استفاده می‌کنی.
همچنین از Microsoft Teams به عنوان پیام‌رسان استفاده خواهد شد.
اگه سوال یا فیدبکی داشتی می‌تونی به اعضای تیمِ ما در این پیام‌رسان پیام بدی و مشکلت رو بر طرف کنی.

<p align="center">
  <img width="100%"  src="https://github.com/Star-Academy/codestar-internship/blob/master/Projects/onboarding_header.png">
</p>

بخشی از فرآیند خوش‌آمدگوییت خودآموزه تا تو رو برای دورکاری و ارتباط برقرار کردن مجازی با سایر هم دوره‌ای‌هات، راهبرها و راهنماها آماده بکنه.
تسک‌هایی که در این
issue
برات آماده شده رو لزوما نباید در روز اول انجام بدی و بیشتر این کارها برای آشناییته پس خیال نکن حتما باید همان روز اول اون‌ها رو انجام بدی.
در صورتی که در پیشبرد این کارها با مشکلی رو به رو شدی اصلا در
mention
کردن راهبر `[آی دی راهبر]` یا همیارت  `[آی دی همیار]`  تردید نکن، اون‌ها وظیفه دارند مشکلاتت رو حل کنن پس نگران نباش و راحت و بدون تعارف از اون‌ها در زیر همین
issue
راهنمایی و کمک بخواه.

هدف از این
issue
این نیست که تمامشون رو به خاطر بسپاری بلکه هدف اینه که یاد بگیری چطوری با مسائلی که برات پیش میاد برخورد کنی و راه حل اون‌ها رو پیدا کنی.

## قبل از شروع دوره

<details>
  <summary>تسک‌های راهبر</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] قبل از شروع دوره حتما با کارآموزت ارتباط بگیر و اون رو به جشن افتتاحیه دوره دعوت کن. حتما تو پیامت خودت رو معرفی کن و ورودش رو به دوره تبریک بگو
  2. [ ] <span  dir="rtl" align='right'> ایمیل کارآموزت رو بگیر و به تیم Microsoft Teams دعوتش کن </span>
  3. [ ] <span  dir="rtl" align='right'> فرآیند خوش‌آمدگویی رو به صورت issue و با عنوان `[نام و نام خانوادگی کارآموز]` تعریف کن ولی assign نکن تا خودش یاد بگیره assign کنه. همچنین جاهایی که نیاز به تغییر داره رو تغییر بده</span>
  4. [ ] یکی از راهنماها رو به عنوان همیار کارآموز انتخاب کن و اون‌ها رو به هم معرفی کن
     </div>
</details>

<details>
  <summary>تسک‌های همیار</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] با کارآموزت ارتباط بگیر و خودت رو معرفی کن
  2. [ ] <span  dir="rtl" align='right'> اگه کارآموزت تو اتصال به Microsoft Teams  مشکل داره مشکلش رو حل کن </span>
  3. [ ] اگر کارآموزت در مورد دوره یا تیم سوالی دارد به طور خلاصه جواب بده و بگو در جلسه افتتاحیه به طور مفصل بیان می‌شه
     </div>
</details>

## مقدمات

حتما این بخش رو در 4 روز اول دوره تکمیل کن.
ممکنه این موارد بیشتر از 4 روز طول بکشه اما امیدواریم که همتون تو هفته اول روی تمام مواردش وقت گذاشته باشین.
اگه یکی از تسک‌هات رو تا پایان روزی که مشخص شده انجام ندادی نگران نباش مشکلی وجود نداره، می‌تونی فرداش بهش مورد رسیدگی کنی.

<details>
  <summary>تسک‌های راهبر</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] `[زمان افتتاحیه]` در افتتاحیه شرکت کن
  2. [ ] هم گروهی‌ هر کارآموز رو مشخص و در جشن اعلام کن
  3. [ ] زمان جلسه روزانه رو با کارآموزت ست کن
     </div>
</details>

<details>
  <summary>تسک‌های همیار</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] `[زمان افتتاحیه]` در افتتاحیه شرکت کن
  2. [ ] کارآموزت رو به گیت‌هاب دعوت کن و اگه توضیح اضافی در این مورد خواست بهش بده
     </div>
</details>

<details>
  <summary>تسک‌های کارآموز</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] `[زمان افتتاحیه]` در افتتاحیه شرکت کن
  2. [ ] به هم گروهیت پیام بده و با هم ارتباط بگیرید
  3. [ ] از همیارت پیگیری کن که به گیت‌هاب اضاف‌ بشی
  4. [ ] <span  dir="rtl" align='right'> به ریپو [codestar-intern-issues](https://github.com/Star-Academy/codestar-intern-issues) برو و در اونجا تسک فرآیند خوش‌آمدگوییت رو پیدا و به خودت assign کن </span>
  5. [ ] <span  dir="rtl" align='right'> با راهبرت یک زمان برای جلسه گزارش روزانه ست کن که هر روز به همراه هم گروهی‌ات با راهبر جلسه داشته باشین. پیشنهاد می‌شه این زمان عصر و در انتهای زمان روزانه باشه</span>
  6. [ ] <span  dir="rtl" align='right'> فاز اول پروژه رو با هم گروهی‌ات شروع کن در 9 فاز اول به ازای هر دو نفر یک ریپوی Github داریم که کد شما در آن ریپو توسعه داده می‌شه و هر فاز تغییر پیدا می کنه
ریپو ها از قبل ساخته شده و اسم ریپو ها با شماره تیم مشخص شده (مثلا گروه 1 و گروه 2 و ...) </span>
  7. [ ] <span  dir="rtl" align='right'> وقتی تسک‌های روز  انجام شد رو انجام دادی لیبل "Day 1- Complete Label" رو به ایشوت متصل کن </span>
     </div>
</details>

## مسائل روزانه

توجه داشته باش هر روز جلسات روزانه با هم تیمی و راهبرت برگزار بشه و همچنین حتما در کلاس‌هایی که راهنماها برگزار می‌کنن حضور پیدا کن.

<details>
  <summary>تسک‌های راهبر</summary>
  
  <div  dir="ltr" align='left'>
  
  * هر روز جلسه روزانه رو برگزار و روند رشد کارآموزها رو بررسی کن
     </div>
</details>

<details>
  <summary>تسک‌های کارآموز</summary>
  
  <div  dir="ltr" align='left'>
  
  * هر روز با هم گروهیت یک جلسه روزانه برگزار کرده و برنامه کاری آن رو مشخص کنید
  * عصرها به جلسه با راهبرت برو و گزارشی از مشکلات یا اتفاقات روزانه ارائه بده
     </div>
</details>

## هفته اول

<details>
  <summary>تسک‌های کارآموز</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] <span  dir="rtl" align='right'> با سه نفر از اعضای بقیه تیم ها جلسه [Coffee Chat](https://about.gitlab.com/company/culture/all-remote/informal-communication/#coffee-chats) برنامه ریزی کن و سعی کن بیشتر با بقیه بچه‌ها در این جلسات آشنا بشی. مدت زمان پیشنهادی برای این جلسات نیم ساعته </span>
  2. [ ] <span  dir="rtl" align='right'>وقتی تسک‌های هفته اول انجام شد رو انجام دادی لیبل "Week 1- Complete Label" رو به ایشوت متصل کن </span>
     </div>
</details>

## هفته دوم

<details>
  <summary>تسک‌های راهبر</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] یک جلسه [یک به یک](https://knowyourteam.com/blog/2018/01/03/7-ways-to-prepare-for-an-effective-one-on-one-meeting-with-your-manager/) با کارآموز برنامه‌ریزی کن و در مورد موارد مختلف جهت آشنایی بیشتر گفت و گو کنید
     </div>
</details>

<details>
  <summary>تسک‌های کارآموز</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] به جلسه [یک به یک](https://knowyourteam.com/blog/2018/01/03/7-ways-to-prepare-for-an-effective-one-on-one-meeting-with-your-manager/) با راهبرت برو
  2. [ ] <span  dir="rtl" align='right'>وقتی تسک‌های هفته دوم انجام شد رو انجام دادی لیبل "week 2- Complete Label" رو به ایشوت متصل کن </span>
     </div>
</details>

## هفته سوم

<details>
  <summary>تسک‌های راهبر</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] <span  dir="rtl" align='right'> یک جلسه [AMA](https://about.gitlab.com/company/culture/all-remote/learning-and-development/#ask-me-anything-ama-group-conversations-and-key-meetings) میان 4 نفر از بچه‌ها و یکی از مدیران ستاره برنامه ریزی کن و به اطلاع کارآموز برسون</spam>
     </div>
</details>

<details>
  <summary>تسک‌های کارآموز</summary>
  
  <div  dir="ltr" align='left'>
  
  1. [ ] <span  dir="rtl" align='right'> در جلسه [AMA](https://about.gitlab.com/company/culture/all-remote/learning-and-development/#ask-me-anything-ama-group-conversations-and-key-meetings) شرکت کن و هر چیزی که در مورد تیم ستاره، گذشته‌، حال و آینده‌اش دوست داری بپرس </span>
  2. [ ] <span  dir="rtl" align='right'> وقتی تسک‌های هفته سوم انجام شد رو انجام دادی لیبل "week 3- Complete Label" رو به ایشوت متصل کن </span>
     </div>
</details>

در صورتی که برای بهبود این قالب پیشنهادی داری لطفا یک
merge request
ایجاد کن و اون رو به
@Star-Academy/people-experience-associate
واگذار کن تا در بهبود سند خوش‌آمدگویی برای دوستانی که در دوره‌های آینده شرکت می‌کنن سهیم باشی.
اگه با فرآیند
merge request
آشنایی نداری و دوست داری در این کار سهیم باشی از همیارت کمک بگیر.

</div>

**Comment by mhaghighat20** [comment]
لطفا اینجا نذار که با ایشو های داک ها قاطی نشه
@mostmand

**Comment by mostmand** [comment]
داشتم تست می‌کردم

**Comment by mhaghighat20** [comment]
این ریپو رو برای بچه ها در نظر گرفتیم
https://github.com/Star-Academy/codestar-intern-issues/issues
