### ISSUE TITLE
تغییر پوشه‌بندی مستندات پروژه‌ها

### ISSUE THREAD

**Issue by ahmadsalimi** [Star-Academy/codestar-internship#38]
<div dir="rtl">
بنظرم از اونجایی که بعضی از فازها ریسورس‌هایی مثل عکس یا فایل های مورد نیاز پروژه دارن، بهتره ساختار پوشه بندی رو طوری تغییر بدیم که هر فاز فولدر خودش رو داشته باشه و ریسورس هاش هم تو همون باشه که دسترسی بهشون ساده تر بشه.
یعنی به این صورت باشه:
</div>

    - Projects
    |---- Phase0
         |---- Phase0.md
         .
         .
         .
    |---- Phase1
    .
    .
    .

**Comment by mhaghighat20** [comment]
برای فاز 6 چون هنوز رلیز نشده و لینکی به جایی نداره به نظرم این کار رو انجام بدیم و از این به بعد هر فازی که طراحی میشه اگه ریسورس داره به صورت پوشه باشه
@ahmadsalimi
