### ISSUE TITLE
مراحل بیشتر برای فاز اول

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#4]
من پیشنویس فاز اول رو نوشتم لطفا بررسی کنین و نظر بدین، به نظرتون لازمه مراحل دیگه‌ای به فاز اول (که کلاً جاوا هست) اضافه کنیم؟

یونیت تست و پایپلاین دو تا از گزینه ها هستن، نظرتون چیه؟ من خودم با یونیت تست موافقم و با پایپلاین مخالفم
برای یونیت تست جاوا فکر می کنم این ویدیو عالی باشه:

https://www.aparat.com/v/KsdQJ

**Comment by mhaghighat20** [comment]
اضافه شدن مراحل مطالعه مربوط با اصول 
SOLID
 و تکنیک های ریفکتور رو قبل از گام یونیت تست پیشنهاد می کنم

**Comment by mhaghighat20** [comment]
Any Idea? @ahmadsalimi @mostmand @alrz1999

**Comment by ahmadsalimi** [comment]
من هم با یونیت تست و هم با سالید موافقم!

**Comment by mhaghighat20** [comment]
چند ساعت بعد به این نتیجه رسیدم اگه تعریف فاز ها رو کوچیک تر کنیم و هر فاز (مخصوصا فاز های اولیه) کار هایی رو در بر بگیره و روی یک یا دو موضوع خاص تمرکز کنه که حدود یک تا سه روز کاری زمان ببره شاید بهتر باشه

بر همین مبنا این مسائل رو توی ایشو تدوین فاز سه آوردم #17
