### ISSUE TITLE
Choose best messenger for internship

### ISSUE THREAD

**Issue by mhaghighat20** [Star-Academy/codestar-internship#5]
در مورد پیام رسان کارآموزی باید فکر کنیم، سه تا گزینه به ذهنم میرسه
* اسلک
* مایکروسافت تیم
* تلگرام

اگه گزینه‌ی دیگه‌ای مد نظرتون هست بگین و مقایسه شون کنیم در نهایت یکی رو انتخاب کنیم
یه موضوعی که هر چی میگذره بیشتر مفید بودنشو بیشتر حس می کنم مفهوم ترد و چنل توی اسلک و مایکروسافت تیم هست که متاسفانه تلگرام و اسکایپ اونو ندارن و برای هر کاری باید گروه بزنیم، که این کار مشکلات دیگه ای ایجاد می کنه

**Comment by mahdimalverdi** [comment]
من نظرم روی مایکروسافت تیمه
اینکه به راحتی قابلیت داره که به بقیه سیستم ها متصل بشه و هم تماس صوتی و تصویری و همه چیز داره و قشنگ میشه توش ترد بحث ایجاد کرد و هزارتا چیز دیگه میگم مایکروسافت تیمز بهترینه

**Comment by mhaghighat20** [comment]
همه با مایکروسافت تیم موافقید؟
@ahmadsalimi @mostmand @mhgheisarieh @alrz1999

**Comment by mhgheisarieh** [comment]
من حقیقتش مایکروسافت تیم رو باهاش کار نکردم ولی خب با تلگرام که اصلا موافق نیستم.   
با این اوصافی که تو و مهدی گفتین مایکروسافت تیم بهتره.

**Comment by mostmand** [comment]
من با مایکروسافت تیم  کار نکردم اگه میگین خوبه خپبه دیگه!

**Comment by ahmadsalimi** [comment]
منم کار نکردم باهاش ولی جذاب به نظر می‌رسه. همون مایکروسافت تیم اوکیه بنظر

**Comment by alrz1999** [comment]
منم با مایکروسافت تیم کار نکردم ولی اگه این ویژگی ها رو داره خیلی خوبه

**Comment by mahdimalverdi** [comment]
باشه پس من بسترش رو آماده می کنم

**Comment by mhaghighat20** [comment]
> 
> 
> باشه پس من بسترش رو آماده می کنم

خیلی هم عالی، لطفا آماده شد لینکش رو اینجا بذار
