### ISSUE TITLE
شروع جلسات یک به یک و توضیح فرآیند کلی

### ISSUE THREAD

**Issue by mahdimalverdi** [Star-Academy/codestar-internship#6]
نیاز است قبل از جشن شروع دوره با تک تک بچه ها جلسه یک به یک برگزار گردد و با آنها در مورد کلیت دوره اهدافشون، تصوراتی که دارند، نیازهایی که ممکنه داشته باشند، علاقه مندی هاشون، اینکه اگه دوست دارند با کسی هم تیمی باشند صحبت بشه

**Comment by mhaghighat20** [comment]
به نظرم بعد از افتتاحیه باشه بهتره

**Comment by mhaghighat20** [comment]
در برنامه هفته اول و دوم و سوم ایشوی خوشآمد گویی گنجانده شد
