### ISSUE TITLE
برگزاری جلسه تقسیم بندی وظایف راهبرها و راهنماها

### ISSUE THREAD

**Issue by mahdimalverdi** [Star-Academy/codestar-internship#7]
در اسرع وقت باید یک جلسه برای تعیین افراد راهبر و راهنما تشکیل شود و شرح وظایف آن‌ها تعیین و به آن‌ها داده شود
اگر نیاز به آموزش خاصی دیده می‌شود باید سریعا برای آن اقدام کرد

**Comment by mhaghighat20** [comment]
موافقم ولی پیشنیاز اون تدوین پیشنویس مسئولیت های راهبر و راهنماست که توی ایشو #10 انجام میشه

**Comment by mhaghighat20** [comment]
done!
