### ISSUE TITLE
آپلود فیلم کارگاه‌ها بر بستر آپارات

### ISSUE THREAD

**Issue by mahdimalverdi** [Star-Academy/codestar-internship#8]
برگزاری کلاس‌ها رو پیشنهاد میکنم بر بستر آپارات برگزار شود

**Comment by mhaghighat20** [comment]
باید بیشتر بررسی کنیم، آیا همه کارگاه ها و افتتاحیه رو ضبط کنیم و روی آپارات قرار بدیم؟
داشتم مطالعه می کردم ظاهرا گیتلب این کارو می کنه و اکثر جلساتش رو روی یوتیوب میذاره اما به نظر میرسه این کار سربار زیادی داشته باشه


دوستان نظر بدین
@mostmand @ahmadsalimi @alrz1999

**Comment by mahdimalverdi** [comment]
سربارش خیلی نیس و به اون هدف کناری که داریم می تونیم به راحتی دست پیدا کنیم با این سبک

**Comment by ahmadsalimi** [comment]
گزینه‌ی دیگه‌ای وجود داره؟
یا کلا بحث اینه که بذاریم آپارات یا یوتیوب یا نه؟

**Comment by alrz1999** [comment]
واسه آپارات یا یوتیوب غیرضبط کردن جلسه چه سرباری داره؟
اگه هم میشد مثل 
udacity
باشه هم جالب میشد

**Comment by mahdimalverdi** [comment]
بحث محمد؛ گذاشتن یا نذاشته
حالا آپارات یوتیوب هرجا اونش مهم نیس

**Comment by mhaghighat20** [comment]
اگه بتونیم همه کارگاه ها و جلسات رو با استاندارد سطح بالایی برگزار کنیم من اوکیم ویدیو ها رو منتشر کنیم

**Comment by mahdimalverdi** [comment]
خیلی هم عالی پس من کانال آپاراتش رو میزنم
