### ISSUE TITLE
ایجاد برد برای هر گروه

### ISSUE THREAD

**Issue by mahdimalverdi** [Star-Academy/codestar-internship#9]
نیاز است برای هر گروه یک برد ایجاد شود و تسک‌ها در آن مشخص شود و همچنین بچه ها از میزان پیشرفت خود مطلع شوند
من پیشنهادم استفاده از برد Azure یا گیت‌هاب است

**Comment by mhaghighat20** [comment]
مهدی فکر می کنم الآن وقتش نیست، وقتی به پروژه های اصلی  و پیچیده تر رسیدیم میشه بهش فکر کرد اما فاز های اولیه خیلی خوشتعریف هست و فکر می کنم کل تقسیم کار در حد یک جلسه باشه، اگه هم تیمی به این نتیجه برسه که نیاز به چنین تقسیم کاری داشته باشه باید خودشون این مسئله رو مطرح کنن و جمع بندی کنن، اگر ما از قبل چنین چیزی تعیین کرده باشیم حس میکنم 
Self-Organize
بودن تیم ها رو نقض کردیم چون این جزء مسائل داخلی تیم هاست

**Comment by mahdimalverdi** [comment]
حالا خیلی منظورم تسک نیس بیشتر یه چیزی مثل okr منظورمه

**Comment by mhaghighat20** [comment]
خب برای OKR
می تونیم فکر کنیم راه های مختلفی هست
بذار یکم بیشتر فکر کنم

**Comment by mahdimalverdi** [comment]
اوکی اما حتما برنامه داشته باشیم

**Comment by mhaghighat20** [comment]
با توجه به وضعیت فعلی و چک لیست داشتن هر فاز و مشخص بودن میزان پیشرفت تیم ها فکر کنم نیازی به زیرساخت بورد و ... در حال حاضر نداریم
